function [TM] = getTransMat(RollAngle, PitchAngle, YawAngle)
% transformation matrix
TM = [cos(PitchAngle)*cos(YawAngle), ... 
      cos(PitchAngle)*sin(YawAngle), ... 
      -sin(PitchAngle);
      sin(RollAngle)*sin(PitchAngle)*cos(YawAngle)-cos(RollAngle)*sin(YawAngle), ...
      sin(RollAngle)*sin(PitchAngle)*sin(YawAngle)+cos(RollAngle)*cos(YawAngle), ...
      sin(RollAngle)*cos(PitchAngle);
      cos(RollAngle)*sin(PitchAngle)*cos(YawAngle)+sin(RollAngle)*sin(YawAngle), ...
      cos(RollAngle)*sin(PitchAngle)*sin(YawAngle)-sin(RollAngle)*cos(YawAngle), ...
      cos(RollAngle)*cos(PitchAngle)];
end